// @vitest-environment jsdom
import React from 'react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { cleanup, render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { BulkPaymentPage } from '../client/src/pages/BulkPaymentPage';
const state = vi.hoisted(() => ({ data: {} }));
vi.mock('../client/src/useStore', () => ({ useStore: () => state.data }));
vi.mock('../client/src/context/RoleContext', () => ({ useRole: () => ({ isCFO: true }) }));
vi.mock('../client/src/store', () => ({ addProfitRecord: vi.fn() }));
const row = (id, profitPending = 300) => ({ id, partnerId: id, partner: { name: id }, amountRupees: 10000, profitPercent: 3, profitPending, isFullyReturned: false });
beforeEach(() => { vi.stubGlobal('React', React); state.data = { hasData: false, status: 'loading', allocationSummaries: [] }; });
afterEach(() => { cleanup(); vi.unstubAllGlobals(); });
it('initializes after cold loading, preserves deselection and leaves new/changed rows for review', async () => {
  const user = userEvent.setup();
  const ui = <MemoryRouter><BulkPaymentPage /></MemoryRouter>;
  const view = render(ui);
  expect(screen.queryByText(/All payments are up to date/)).toBeNull();
  state.data = { hasData: true, status: 'ready', isStale: false, allocationSummaries: [row('Arun')] }; view.rerender(<MemoryRouter><BulkPaymentPage /></MemoryRouter>);
  await user.click(screen.getByRole('button', { name: /Deselect Arun/ }));
  state.data = { ...state.data, allocationSummaries: [row('Arun'), row('Priya')] }; view.rerender(<MemoryRouter><BulkPaymentPage /></MemoryRouter>);
  expect(screen.getByRole('button', { name: /Select Arun/ }).getAttribute('aria-pressed')).toBe('false');
  expect(screen.getByRole('button', { name: /Select Priya/ }).getAttribute('aria-pressed')).toBe('false');
  await user.click(screen.getByRole('button', { name: /Select Priya/ }));
  await user.click(screen.getByRole('button', { name: /Review 1 payment/ }));
  await user.clear(screen.getByLabelText('Partner + CFO amount (₹) *'));
  await user.type(screen.getByLabelText('Partner + CFO amount (₹) *'), '150');
  state.data = { ...state.data, allocationSummaries: [row('Arun'), row('Priya')] }; view.rerender(<MemoryRouter><BulkPaymentPage /></MemoryRouter>);
  expect(screen.getByLabelText('Partner + CFO amount (₹) *').value).toBe('150');
  state.data = { ...state.data, allocationSummaries: [row('Priya', 200)] }; view.rerender(<MemoryRouter><BulkPaymentPage /></MemoryRouter>);
  expect(screen.getByRole('heading', { name: /Step 1/ })).toBeTruthy();
  expect(screen.queryByRole('button', { name: /Select Arun/ })).toBeNull();
  expect(screen.getByRole('button', { name: /Select Priya/ }).getAttribute('aria-pressed')).toBe('false');
  await user.click(screen.getByRole('button', { name: /Select Priya/ }));
  await user.click(screen.getByRole('button', { name: /Review 1 payment/ }));
  expect(screen.getByLabelText('Partner + CFO amount (₹) *').value).toBe('150');
  state.data = { ...state.data, status: 'error', isStale: true }; view.rerender(<MemoryRouter><BulkPaymentPage /></MemoryRouter>);
  expect(screen.queryByLabelText('Partner + CFO amount (₹) *')).toBeNull();
});
