export type CashbackStatus = 'review' | 'unpaid' | 'paid' | 'not_applicable';
type CashbackMetadata = { notes?: string; updatedAt?: string; createdAt?: string; selectionUpdatedAt?: string; individualStatus?: boolean };
export type Cashback = CashbackMetadata & ({ status: Exclude<CashbackStatus, 'paid'> } | { status: 'paid'; amountRupees: number | null; paidDate: string });
export type CashbackSelection = { cashbackOtherPaidAllocationIds?: string[]; cashbackEligibility?: string; cashbackSelectedAllocationId?: string | null; cashbackSelectionStatus?: string | null; cashbackSelectionUpdatedAt?: string | null };
type Allocation = CashbackSelection & { id?: string; creditCardId?: string | null; combination?: unknown; cashback?: Cashback | null };
export function cashbackStatus(allocation: Allocation): CashbackStatus;
export function validateCashback(input: unknown, allocation: Allocation & { receivedDate: string }, today: string): Cashback;
export function prepareCashback(input: unknown, allocation: Allocation & { receivedDate: string }, today: string, now?: string): Cashback;
export function cashbackTotals(allocations: { cashback?: Cashback | null }[]): { totalCashbackPaid: number; unknownCashbackCount: number };
export function monthlyCashback<T extends { id: string; creditCardId?: string | null; receivedDate: string; combination?: unknown; cashback?: Cashback | null }>(allocations: T[]): (T & CashbackSelection)[];
